name: pytest

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        debian-version: [ "11", "12", "13" ]
        sqlalchemy-version: [ "1.4" ]
        include:
          - debian-version: "11"
            python-version: "3.9"
            postgres-version: "13"
            postgis-version: "3.2"
          - debian-version: "12"
            python-version: "3.11"
            postgres-version: "15"
            postgis-version: "3.3"
          - debian-version: "13"
            python-version: "3.13"
            postgres-version: "17"
            postgis-version: "3.5"

    name: Debian ${{ matrix.debian-version }} - SQLAlchemy ${{ matrix.sqlalchemy-version }}

    services:
      postgres:
        image: postgis/postgis:${{ matrix.postgres-version }}-${{ matrix.postgis-version }}
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Add database extensions
      run: |
        psql -h localhost -U postgres -d postgres -tc 'CREATE EXTENSION "postgis_raster";'
        psql -h localhost -U postgres -d postgres -tc 'CREATE EXTENSION "uuid-ossp";'
        psql -h localhost -U postgres -d postgres -tc 'CREATE EXTENSION "pg_trgm";'
        psql -h localhost -U postgres -d postgres -tc 'CREATE EXTENSION "unaccent";'
        psql -h localhost -U postgres -d postgres -tc 'CREATE EXTENSION "ltree";'
      env:
        PGPASSWORD: postgres
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install \
          pytest-cov \
          -e .[tests] \
          -e file:dependencies/Utils-Flask-SQLAlchemy#egg=utils-flask-sqlalchemy \
          -e file:dependencies/TaxHub#egg=taxhub \
          -e file:dependencies/TaxHub/dependencies/RefGeo#egg=pypn-ref-geo
    - name: Install database
      run: |
        flask db upgrade taxonomie@head -x local-srid=2154
        flask db upgrade ref_geo@head -x local-srid=2154
        flask db upgrade nomenclatures_taxonomie@head
        flask db autoupgrade
        flask taxref import-v17 --skip-bdc-statuts
        flask db upgrade nomenclatures_taxonomie_data@head
      env:
        NOMENCLATURE_SETTINGS: test_settings.py
    - name: Test with pytest
      run: |
        pytest -v --cov --cov-report xml
      env:
        NOMENCLATURE_SETTINGS: test_settings.py
    - name: Upload coverage to Codecov
      if: ${{ matrix.debian-version == '12' && matrix.sqlalchemy-version == '1.4' }}
      uses: codecov/codecov-action@v3
      with:
        flags: pytest
